- name: configure wireless network
  tags: wireless-network
  block:
  - name: Install system dependencies
    apt:
      name:
      - wpasupplicant
  - name: Configure wpa_supplicant
    become: yes
    template:
      src: wpa_supplicant.conf.j2
      dest: /etc/wpa_supplicant/wpa_supplicant.conf
      backup: yes
  - name: disable the rf kill switch
    become: yes
    command: "rfkill unblock wlan"
  - name: make wpa_supplicant re-read it's configuration file
    become: yes
    command: "wpa_cli -i wlan0 reconfigure"
    notify: Restart Networking
