---
- tags: network
  become: yes
  block:
    - name: configure network interfaces
      copy:
        dest: /etc/network/interfaces
        content: |
          source /etc/network/interfaces.d/*

          auto lo
          iface lo inet loopback

    - name: configure network interfaces
      copy:
        src: etc/network/interfaces.d/{{ ansible_hostname }}
        dest: /etc/network/interfaces.d/{{ ansible_hostname }}

    - name: configure name resolution
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
          nameserver 8.8.4.4
