- tags:
    - lxc-guest
  become: true
  block:
    - name: Remove default packages
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      with_items:
        - isc-dhcp-client
        - ifupdown
