# NOTE(mastensg): exclude hosts which have their own ansible directories.
- hosts: all,!bomba,!boxy2,!boxy3,!boxy3-workshop,!boxy4,!heim,!p2k16,!p2k16-staging
  roles:
    - bitraf-base
    - lusers
    - superusers

- hosts:
    # TODO: the ignores hosts can use this role, it just have to be
    # checked that it work.
    - all !iot !mysql
  roles:
    - role: unattended-upgrades
      become: yes

# NOTE(mastensg): the riemann-health roles should not conflict with per-host
# ansible playbooks.
- hosts: all !bomba
  roles:
    - riemann-health
