- hosts: mediawiki
  vars:
    lan: "{{ host_database | json_query(ansible_hostname + '.interfaces | * | [?role==`lan`]') | first }}"
    db: "{{ host_database | json_query(mediawiki.db.host + '.interfaces | * | [?role==`lan`]') | first }}"
  roles:
    - bitraf-base
    - lxc-guest
    - packages
    - lusers
    - superusers
    - postfix-satellite
    - role: nginx
      nginx__template:
        - sites-enabled/default
        - sites-enabled/mediawiki
      w: w2
      wiki: wiki2
      ipv4: "*"
      ipv6: "[::]"
    - role: mediawiki
      mediawiki__local_settings: mediawiki/LocalSettings.php
      mediawiki__wgDBserver: "{{ db.ipv4.address }}"
      mediawiki__wgDBname: "{{ mediawiki.db.name }}"
      mediawiki__wgDBuser: "{{ mediawiki.db.user }}"
      mediawiki__wgDBpassword: "{{ mediawiki.db.password }}"

  tasks:
    - name: Clone Bitraf's skin
      tags:
        - mediawiki
        - bitraf-skin
      become: yes
      git:
        repo: https://github.com/bitraf/mediawiki-skin-bitraf
        dest: /opt/mediawiki/mediawiki/skins/Bitraf

    - name: "Extension: googleAnalytics"
      tags:
        - mediawiki
        - mediawiki-extensions
      become: yes
      with_items:
        - repo: https://github.com/bitraf/Wikilog.git
          dest: Wikilog
          version: e6c86ee98ffc68eb4cd68e376afdedee15e10fd8
        - repo: https://github.com/wikimedia/mediawiki-extensions-googleAnalytics
          dest: googleAnalytics
          version: REL1_31
        - repo: https://github.com/wikimedia/mediawiki-extensions-CharInsert
          dest: CharInsert
          version: REL1_31
        - repo: https://github.com/wikimedia/mediawiki-extensions-Scribunto
          dest: Scribunto
          version: REL1_31
        - repo: https://github.com/wikimedia/mediawiki-extensions-CodeEditor
          dest: CodeEditor
          version: REL1_31
      git:
        repo: "{{ item.repo }}"
        dest: "/opt/mediawiki/mediawiki/extensions/{{ item.dest }}"
        version: "{{ item.version }}"

    - name: Install local extensions
      become: yes
      tags:
        - mediawiki-extensions
      with_items:
        - extensions/GoogleTagManager
      file:
        path: "/opt/mediawiki/mediawiki/{{ item }}"
        state: directory

    - name: Install local extensions
      become: yes
      tags:
        - mediawiki-config
        - mediawiki-extensions
        - p2k12-auth
      with_items:
        - p2k12-auth.php
        - GoogleTagManager/GoogleTagManager.i18n.php
        - GoogleTagManager/GoogleTagManager.php
      copy:
        dest: "/opt/mediawiki/mediawiki/extensions/{{ item }}"
        src: "mediawiki/{{ item }}"
