---
- name: grafana
  become: yes
  tags:
    - grafana
  block:
    - name: Grafana APT key
      notify: update apt cache
      copy:
        dest: /etc/apt/keyrings/grafana.gpg
        src:   etc/apt/keyrings/grafana.gpg

    - name: Grafana APT repository
      notify: update apt cache
      copy:
        dest: /etc/apt/sources.list.d/grafana.list
        content: 'deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main'

    - meta: flush_handlers

    - name: packages
      apt:
        name: "{{ item }}"
        install_recommends: no
      with_items:
        - grafana

    - name: enable systemd unit
      systemd:
        name: "grafana-server.service"
        daemon_reload: yes
        enabled: yes
        state: started
