# Inspired from https://github.com/debops/ansible-mosquitto/blob/master/tasks/main.yml
# I had an idea that the file could be conditionally updated and thus
# could save a reload of the server, but mosquitto_passwd always uses a
# new salt so the file will always be different.
#
# Instead just update the existing file in-place.
#
# TODO: Change all passwords and generate the password file from
# scratch instead of updating.
---
- name: Install ignore file for etckeeper
  copy: 
    src: "etc/mosquitto/.gitignore"
    dest: "/etc/mosquitto/.gitignore"

- name: Install files
  tags: mosquitto-files
  block:
    - name: Configuration files
      copy:
        src: "{{ item }}"
        dest: "/{{ item }}"
      with_items:
        - etc/mosquitto/mosquitto.conf
        - etc/mosquitto/bitraf.acl

    - name: Remove old files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - etc/mosquitto/conf.d/bitraf.passwords
        - etc/mosquitto/conf.d/bitraf.acl
        - etc/mosquitto/conf.d/bitraf.conf

- name: Password management
  tags: mosquitto-passwd
  block:
    - name: Stat passwd file
      stat:
        path: "{{ mosquitto__password_file }}"
      register: orig

    - name: Create passwd file
      file:
        path: "{{ mosquitto__password_file }}"
        state: touch
      when: not orig.stat.exists

    - name: Load passwd file
      command: "cut -f 1 -d : {{ mosquitto__password_file }}"
      changed_when: False
      check_mode: False
      register: mosquitto__passwd

    - name: Remove passwd entries
      command: "mosquitto_passwd -D {{ mosquitto__password_file }} {{ item.name | d(item) }}"
      with_items:
        - "{{ mqtt_accounts }}"
      when: |
        (item.state|d('present') == 'absent') and
        (item.name in mosquitto__passwd.stdout_lines)

    - name: Create passwd entries
      environment:
        PW: "{{ bitraf_passwords.mqtt[item.name].password }}"
      command: "mosquitto_passwd -b {{ mosquitto__password_file }} {{ item.name | d(item) }} ${PW}"
      with_items:
        - "{{ mqtt_accounts }}"
      when: (item.state|d('present') != 'absent')

    - debug:
        msg: Forcing restart of mosquitto
      notify: restart mosquitto
      changed_when: true
