#!/usr/bin/env python3

import json
import os
import yaml

with open(os.getenv("FILE")) as f:
    x = yaml.safe_load(f)

entries = {}

for hostname, host in x["host_database"].items():
    for iface, data in host.get("interfaces", {}).items():
        dns = data.get("dns")
        ipv4 = data.get("ipv4", {}).get("address")
        ipv6 = data.get("ipv6", {}).get("address")
        if dns is None or not dns.endswith(".lan.bitraf.no"):
            continue
        dns = dns[0:-len(".bitraf.no")]
        if ipv4 is not None:
          entries[f"{dns}-a"] = {"name": dns, "type": "A", "target": ipv4}
        if ipv6 is not None:
          entries[f"{dns}-aaaa"] = {"name": dns, "type": "AAAA", "target": ipv6}

print(json.dumps(entries, sort_keys=True, indent=2))
