users:
  - username: eliasbakken
    state: present
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEVoE61UreMtgITTsdSoX2UzBmeLJitKsXRhia7EmJP0
  - username: mastensg
    state: present
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICOayiImJKc7Qfmp2i33QNreBZ+zatorDVP3IUEPXlch mastensg@reed
  - username: trygvis
    state: present
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPX+sVfRvl0+KxsDlbIutyB/Es3exTwNfDVHwi9orwz3 trygvis@birgitte
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJAzB6JB/hZ87M6ozsd7lgKxgOacEOZZRxa4ucs11lqq trygvis@conflatorio
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFJWlDmgPIwkUgljVKiNr2wfHGfz4VVoPvuDLJfMD9LM trygvis@arius-v2
  - username: tingo
    state: present
    authorized_keys: ""
  - username: royk
    state: present
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJlXRj/vYaL3v/ynF4Z1Sc5up9b1hCdfSZv4bLzwLWYv roy@karlsbakk.net
  - username: odinho
    state: present
    authorized_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOXi2hd00LZWMvVNPFGESL2KgmeeuxpYGzjvQU1eESEB odin@h
  - username: haavares
    state: present
    authorized_keys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjyYhjUXvIOg7T2yHGchEt0h03unxPmATeDhE7Lh6BAGbtgdJCDqhZr3FQrT1CLPwaHtNkAbSFKrxe+n+xV4Bh6jzPxc4fVRSUGHz3VrMojtxey7BMo3YmYgj7riHgAFiVg787VtE2tDQwuHoCGdafeSJPZEpUMvfLe4oUG6KE9i2sQpkFCuVharc/grna67NmAIyVxQYqA3KdoUO/i7W3P8bEpDj6s6F6H63iX9quOLmHc1tbS7kAkaB7EVvhOAbsDbo8cpkAFbUOX9UJS4tJfOGMrkTJ6IhO7HyXM6LmoS3sA6EFSYFbdM7UjpVk7/RwJ7WjW2Sm/8MbtIgklo9t haavares@helga-908.local
