---
- hosts: bite
  roles:
    - network
    - packages
    - bitraf-base
    - postfix-satellite
  vars_files:
    - ../group_vars/all/host_database.yml
    - ../vars/postfix.yml
    - ../vars/users.yml
  tasks:
  # The disk array doesn't work nicely with the UAS driver.
  - name: /etc/modprobe.d/blacklist_uas.conf
    become: True
    register: blacklist_uas
    copy:
      dest: /etc/modprobe.d/blacklist_uas.conf
      content: |
        blacklist uas
        options usb-storage quirks=152d:0539:u

  - name: update-initramfs -u -k all
    become: True
    when: blacklist_uas.changed
    shell: /usr/sbin/update-initramfs -u -k all

  - name: lusers
    import_role: name=lusers
    tags: lusers
    become: yes

  - name: superusers
    import_role: name=superusers
    tags: superusers
    become: yes

  - name: lxc-hosts
    import_role: name=lxc-host
    tags: lxc-host
    become: yes

#  - name: "Install machine specific config: {{ item }}"
#    tags:
#     - lxc-host
#     - lxc-host-config
#    become: yes
#    with_items:
##      - marvin
#    copy:
#      dest: "/var/lib/lxc/{{ item }}/config-machine"
#      src: "var/lib/lxc/{{ item }}/config-machine"
