---
- hosts: bite
  roles:
    - network
    - packages
    - users
    - postfix-satellite
  vars_files:
    - ../vars/postfix.yml
  tasks:
  # The disk array doesn't work nicely with the UAS driver.
  - name: /etc/modprobe.d/blacklist_uas.conf
    become: True
    register: blacklist_uas
    copy:
      dest: /etc/modprobe.d/blacklist_uas.conf
      content: |
        blacklist uas
        options usb-storage quirks=152d:0539:u

  - name: update-initramfs -u -k all
    become: True
    when: blacklist_uas.changed
    shell: /usr/sbin/update-initramfs -u -k all

  - name: lxc-hosts
    import_role: name=lxc-host
    tags: lxc-host
    become: yes
