- become: true
  tags:
    - bitraf-base
    - bitraf-base-misc
  block:
    - name: /etc/localtime
      when: bitraf_base__etc_localtime
      file:
        src: /usr/share/zoneinfo/Europe/Oslo
        dest: /etc/localtime
        state: link
        force: yes
      notify: reconfigure tzdata

    - name: remove ~root/.ssh/authorized_keys
      when: bitraf_base__remove_root_authorized_keys
      file:
        path: ~root/.ssh/authorized_keys
        state: absent

    - name: /etc/hosts
      when: bitraf_base__fix_hosts
      copy:
        dest: /etc/hosts
        content: |
          127.0.0.1	localhost
          127.0.1.1	{{ ansible_hostname }}.bitraf.no {{ ansible_hostname }}

          # The following lines are desirable for IPv6 capable hosts
          ::1     localhost ip6-localhost ip6-loopback
          ff02::1 ip6-allnodes
          ff02::2 ip6-allrouters

- become: true
  tags:
    - bitraf-base
    - bitraf-base-syslog
  when: bitraf_base__syslog
  block:
    - name:
      with_items:
        - rsyslog
      apt:
        name: "{{ item }}"
        state: present
        install_recommends: no
