---
- name: configure debian repositories
  tags: packages
  notify: update apt cache
  become: yes
  copy:
    dest: /etc/apt/sources.list
    content: |
      deb     http://ftp.no.debian.org/debian/ stretch main contrib non-free
      deb-src http://ftp.no.debian.org/debian/ stretch main contrib non-free

      deb     http://security.debian.org/debian-security stretch/updates main contrib non-free
      deb-src http://security.debian.org/debian-security stretch/updates main contrib non-free

      deb     http://ftp.no.debian.org/debian/ stretch-updates main contrib non-free
      deb-src http://ftp.no.debian.org/debian/ stretch-updates main contrib non-free

      deb     http://ftp.no.debian.org/debian/ stretch-backports main contrib non-free
      deb-src http://ftp.no.debian.org/debian/ stretch-backports main contrib non-free

- name: install debian packages
  tags: packages
  become: yes
  apt:
    install_recommends: no
    name:
      - aptitude
      - bridge-utils
      - debian-goodies
      - etckeeper
      - hdparm
      - htop
      - iperf
      - ltrace
      - man-db
      - ncdu
      - needrestart
      - netcat-openbsd
      - screen
      - strace
      - tmux
      - tree
      - vim
      - sysstat
      - nmap
      - net-tools
      - avahi-daemon
