---
- hosts: grafana
  roles:
    - network
    - packages
    - bitraf-base
    - lusers
    - superusers
    - influxdb
    - grafana
    - telegraf
  vars_files:
    - ../vars/bitraf_passwords.yml
    - ../vars/users.yml
