---
- hosts:
    - riemann
  tasks:
    - name: download
      become: yes
      fetch:
        src: /etc/riemann-dash/config.json
        dest: roles/riemann-dash/files/etc/riemann-dash/config.json
        flat: yes
