---
- name: configure debian repositories
  tags: packages
  notify: update apt cache
  become: yes
  copy:
    dest: /etc/apt/sources.list
    content: |
      deb     http://ftp.no.debian.org/debian/ bookworm main contrib non-free non-free-firmware
      deb-src http://ftp.no.debian.org/debian/ bookworm main contrib non-free non-free-firmware

      deb     http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
      deb-src http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware

      deb     http://ftp.no.debian.org/debian/ bookworm-updates main contrib non-free non-free-firmware
      deb-src http://ftp.no.debian.org/debian/ bookworm-updates main contrib non-free non-free-firmware

      deb     http://ftp.no.debian.org/debian/ bookworm-backports main contrib non-free non-free-firmware
      deb-src http://ftp.no.debian.org/debian/ bookworm-backports main contrib non-free non-free-firmware


- name: install debian packages
  tags: packages
  become: yes
  apt:
    install_recommends: no
    name:
      - aptitude
      - bridge-utils
      - debian-goodies
      - etckeeper
      - iperf
      - ltrace
      - ncdu
      - needrestart
      - net-tools
      - netcat-openbsd
      - nmap
      - screen
      - strace
      - sysstat
      - tmux
      - tree
      - vim
