- become: yes
  block:
    - name: Packages for WAL-E
      apt:
        name: "{{ items }}"
        install_recommends: no
      vars:
        items:
          - pv
          - lzop

    - name: pip
      become: yes
      become_user: postgres
      pip:
        name: "{{ items }}"
        virtualenv: "{{ pwe_venv }}"
        virtualenv_python: python3
      vars:
        ansible_ssh_pipelining: true
        items:
          - wal-e
          - envdir

    - name: Config dir
      file:
        path: /etc/wal-e/{{ pwe_major }}-{{ pwe_instance }}-env.d
        state: directory
        mode: u=rwx,g=rx,o=
        group: postgres

    - name: Config entry
      notify: restart postgresql
      copy:
        dest: "/etc/wal-e/{{ pwe_major }}-{{ pwe_instance }}-env.d/{{ item.key }}"
        content: "{{ item.value }}"
        mode: u=rwx,g=rx,o=
        group: postgres
      with_items:
        - key: "WALE_FILE_PREFIX"
          value: "file://localhost/var/lib/postgresql/backups"

    - name: PostgreSQL config
      notify: restart postgresql
      copy:
        dest: /etc/postgresql/{{ pwe_major }}/{{ pwe_instance }}/conf.d/bitraf-backup.conf
        content: |
          wal_level = archive
          archive_mode = on
          archive_command = '{{ pwe_venv }}/bin/envdir /etc/wal-e/{{ pwe_major }}-{{ pwe_instance }}-env.d {{ pwe_venv }}/bin/wal-e wal-push %p'
          archive_timeout = 60

    - name: systemd base backup service
      register: base_backup_service
      copy:
        dest: /etc/systemd/system/postgresql-base-backup@.service
        content: |
          [Unit]
          Description=PostgreSQL base backup

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/env bash -c 'i="%i"; i=${i/-//}; bin/envdir /etc/wal-e/%i-env.d bin/wal-e backup-push /var/lib/postgresql/$i'
          WorkingDirectory={{ pwe_venv }}
          User=postgres

    - name: systemd base backup timer
      register: base_backup_timer
      copy:
        dest: /etc/systemd/system/postgresql-base-backup@.timer
        content: |
          [Unit]
          Description=PostgreSQL base backup timer

          [Timer]
          OnCalendar=Sun 04:00

          [Install]
          WantedBy=timers.target

    - name: systemd daemon-reload
      when: base_backup_service.changed or base_backup_timer.changed
      systemd:
        daemon_reload: yes
        enabled: yes
        masked: no
        name: postgresql-base-backup@{{ pwe_major }}-{{ pwe_instance }}.timer
