superusers:
  - username: mastensg
    state: present
  - username: trygvis
    state: present
  - username: talimere
    state: present
  - username: tingo
    state: present
  - username: eliasbakken
    state: present
