---
- name: configure network interfaces
  tags: network
  become: yes
  copy:
    dest: /etc/network/interfaces
    content: |
      source /etc/network/interfaces.d/*

      auto lo
      iface lo inet loopback

- name: configure bitraf network interfaces
  tags: network
  become: yes
  copy:
    dest: /etc/network/interfaces.d/bitraf
    content: |
      auto enp4s0f0
      iface enp4s0f0 inet manual

      auto br0
      iface br0 inet static
              bridge_ports enp4s0f0
              address 10.13.37.3
              netmask 255.255.255.0
              post-up iptables -A FORWARD -p all -i br0 -j ACCEPT

      auto enp4s0f1
      iface enp4s0f1 inet manual

      auto br1
      iface br1 inet static
              bridge_ports enp4s0f1
              address 77.40.158.102
              netmask 255.255.255.224
              gateway 77.40.158.97
              post-up iptables -A FORWARD -p all -i br1 -j ACCEPT
      iface br1 inet6 static
              address 2001:8c0:ea04:10:77:40:158:102
              netmask 64
              gateway  2001:8c0:ea04:10::1
              autoconf 0
              dns-nameservers 2001:4860:4860::8888 2001:4860:4860::8844

- name: disable ipv6 autoconf for some interfaces
  tags: network
  become: yes
  sysctl:
    name: "net.ipv6.conf.{{ item }}.autoconf"
    value: 0
    state: present
    reload: yes
  with_items:
    - enp4s0f0
    - br0
    - enp4s0f1
    - br1

- name: configure name resolution
  tags: network
  become: yes
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 8.8.8.8
      nameserver 8.8.4.4
