---
- name: postgresql-server
  become: yes
  tags:
    - postgresql-server-base
  block:
    - name: Install PostgreSQL APT key
      tags: pg
      notify: update apt cache
      apt_key:
        id: ACCC4CF8
        keyserver: keyserver.ubuntu.com

    - name: PostgreSQL APT repository
      tags: pg
      notify: update apt cache
      copy:
        dest: /etc/apt/sources.list.d/postgresql.list
        content: 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main'

- meta: flush_handlers

- become: yes
  tags:
    - postgresql-server-base
    - postgresql-server-base-packages
  block:
    - name: packages
      apt:
        name: "{{ items }}"
        install_recommends: no
      vars:
        items:
          - postgresql-10
          - postgresql-client-10
          - python-psycopg2
          - python3-psycopg2

    - name: Logrotate
      copy:
        dest: /etc/logrotate.d/postgresql-common
        content: |
          # Managed by Ansible
          /var/log/postgresql/*.log {
                 daily
                 dateext
                 copytruncate
                 delaycompress
                 compress
                 notifempty
                 missingok
                 su root root
          }
