#!/bin/bash

set -euo pipefail

for domain in $RENEWED_DOMAINS; do
  case $domain in
  mqtt.bitraf.no)
    umask 077

    certs="/etc/mosquitto/certs"

    cp "${RENEWED_LINEAGE}/fullchain.pem" "${certs}/${domain}-fullchain.pem"
    cp "${RENEWED_LINEAGE}/privkey.pem" "${certs}/${domain}-privkey.pem"

    chown mosquitto "${certs}/${domain}-fullchain.pem" "${certs}/${domain}-privkey.pem"
    chmod 400 "${certs}/${domain}-fullchain.pem" "${certs}/${domain}-privkey.pem"

    systemctl restart mosquitto
    ;;
  esac
done
