---
- tags: superusers
  become: yes
  vars:
    usernames: "{{ users|dict2items|map(attribute='key')|list }}"
  block:
    - name: getent group sudo
      getent:
        database: group

    - name: Grant sudo
      with_items: "{{ superusers }}"
      user:
        name: "{{ item }}"
        groups: sudo,systemd-journal
        append: yes

    - name: Revoke sudo
      with_items: "{{ getent_group['sudo'][2].split(',') }}"
      when: item not in superusers
      shell: "gpasswd --delete {{ item }} sudo"

    - name: "Allow 'sudo' group to have passwordless sudo"
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
