- debug:
    msg: "LXC HOST: {{ i.key }}"

- name: bitraf-config
  register: bitraf_config
  copy:
    dest: "/var/lib/lxc/{{ i.key }}/bitraf-config"
    content: |
      lxc.network.type = veth
      lxc.network.link = br0
      lxc.network.flags = up
      lxc.network.hwaddr = {{ i.value.hwaddr }}
      lxc.network.ipv4 = {{ i.value.ipv4.address }}/{{ i.value.ipv4.netmask }}
      lxc.network.ipv4.gateway = {{ i.value.ipv4.gateway }}
      # 0 = trace, 1 = debug, 2 = info, 3 = notice, 4 = warn, 5 = error, 6 = critical, 7 = alert, and 8 = fatal.
      lxc.loglevel = 1
      lxc.logfile = /var/lib/lxc/{{ i.key }}/{{ i.key }}.log

- name: include file
  register: debian_config_1
  lineinfile:
    path: "/var/lib/lxc/{{ i.key }}/config"
    regexp: "^lxc.include *=.*/debian.common.conf$"
    line: "lxc.include = /usr/share/lxc/config/debian.common.conf"

- name: include file
  register: debian_config_2
  lineinfile:
    path: "/var/lib/lxc/{{ i.key }}/config"
    regexp: "^lxc.include *=.*/bitraf-config$"
    line: "lxc.include = /var/lib/lxc/{{ i.key }}/bitraf-config"

- name: restart lxc container {{ i.key }}
  when: i.value.state == 'started' and (bitraf_config.changed and debian_config.changed_1 and debian_config.changed_2)
  lxc_container:
    name: "{{ i.key }}"
    state: restarted
